# Generated by Django 4.2.7 on 2023-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='image_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
